[phases.setup]
nixpkgsPackages = [
  "php83",
  "php83Packages.composer",
  "php83Extensions.pdo",
  "php83Extensions.pdo_mysql",
  "php83Extensions.mysqli",
  "php83Extensions.mbstring",
  "php83Extensions.openssl"
]

[phases.build]
cmds = ["composer install --no-dev --optimize-autoloader"]

[start]
cmd = "php -S 0.0.0.0:$PORT test.php"

