# zeabur.yaml
services:
  appgro:
    source:
      type: git
    build:
      dockerfile: Dockerfile
    environment:
      APP_ENV: production
      APP_DEBUG: false
    ports:
      - port: 8080
        type: http
